- name: configuring {{COMPONENT}} repos
  ansible.builtin.copy:
   src: redis.repo
   dest: /etc/yum.repos.d/redis.repo

- name: Installing redis
  ansible.builtin.package:
    name: redis-6.2.7
    state: present

- name: Updating {{COMPONENT}} config file
  ansible.builtin.replace:
    path: "{{item}}"
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  loop:
      - /etc/redis.conf
      - /etc/redis/redis.conf


- name: Starting the {{COMPONENT}}
  ansible.builtin.service:
    name: "{{COMPONENT}}"
    state: started
    enabled: yes
