- name: downloading nodjs repo
  ansible.builtin.shell: https://rpm.nodesource.com/setup_lts.x | bash

- name: Installing nodejs
  ansible.builtin.package:
    name: "{{item}}"
    state: present
  loop:
    - nodejs
    - gcc-c++

- name: creating user
  ansible.builtin.include_role:
    name: common
    tasks_from: create-user.yml

- name: Downloading and extracting
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp
    remote_src: yes



  


